logging:
  level:
    root: warn
    org:
      springframework:
        security: warn
      apereo:
        cas: info
casbot:
  github:
    repository:
      organization: apereo
      name: cas
      url: https://github.com/apereo/cas
      admins: mmoayyed,apereocas-bot

security:
  en
spring:
  security:
    user:
      name: apereocasbot
      password: ${CASBOT_GITHUB_CREDENTIALS_TOKEN}
      roles: ADMIN
